### ISSUE TITLE
email report complains has no enough data, while it has

### ISSUE THREAD

**Issue by Jujonet** [emoncms/emailreport#1]
Hi

Some days ago installe the module in my emonSD running in a Rpi2 following the instructions provided.
Installed swiftmailer and updated&Checked the database.

All seemed to work but I get the following warning:

```
Not enough days returned in data request 
Warning: Cannot modify header information - headers already sent by (output started at /home/pi/emailreport/emailreport-module/emailreportgenerator.php:51) in /var/www/emoncms/index.php on line 265

Notice: Array to string conversion in /var/www/emoncms/index.php on line 266
Array
```
If I exectute the script "by hand":

`sudo php /home/pi/emailreport/weekly-cron.php`

I get the following:

```
Sending energy update emails
 - Myemoncmsusername
Not enough days returned in data request
 - Myemoncmsusername

```

For the avoidance of doubt: I have more than 3 weeks of data on the selected feed

Any clue?

Thank you in advance

**Comment by pb66** [comment]
Ref https://community.openenergymonitor.org/t/email-report-complains-has-not-enough-data-while-it-has/7976?u=pb66

This looks like a result of changes in the feed api so that an extra day's is returned for the same api. There are now 9 days not 8 returned.

**Comment by TrystanLea** [comment]
I think this was fixed in https://github.com/emoncms/emailreport/commit/f3e6660653105a00ccc60f86f15ebd83c403af50, please reopen if still an issue.
