### ISSUE TITLE
error accessing emailreport module

### ISSUE THREAD

**Issue by Bigben83** [emoncms/emailreport#3]
when clicking on email report under extras it takes me to a page saying.

Forbidden
You don't have permission to access /emoncms/emailreport/ on this server.

am I doing something wrong ?
Ubuntu 14.04
php 7.2

**Comment by TrystanLea** [comment]
Hello @Bigben83 did you solve this problem? did you install the emailreport module in Modules?  Sounds like permissions level issue when installing the repository? I realise this issue is old and that you have likely moved on, please reopen if needed
